databases:
  - name: smiles
    databaseName: smiles
    user: smiles_user

services:
  - type: web
    name: mysmile
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysmile
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false